services:

  crawler:
    build: crawler/
    container_name: crawler
    environment:
      - CRAWLER_GEO=${CRAWLER_GEO}
      - CRAWLER_PROVIDER=${CRAWLER_PROVIDER}
      - CRAWLER_MEDIUM=${CRAWLER_MEDIUM}
      - AWS_ACCESS_KEY_ID=${LOCAL_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${LOCAL_AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${LOCAL_AWS_SESSION_TOKEN}
      - AWS_REGION=us-east-1
      - VPN=${VPN}
    command: '/srv/init.sh'
    volumes:
      - ./crawler:/srv